### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by wlyra** [pfitsplus/pfitsplus.github.io#3]
The following links are broken:

- [x] "GitHub" - https://lab.github.com/githubtraining/introduction-to-github?overlay=register-box-overlay
- [x] "GitHub wiki guide" - https://github.com/pfitsplus/technical-resources/wiki/Getting-Started#github
- [x] "Syncing your branch" - https://github.com/pfitsplus/technical-resources/wiki/Getting-Started#syncing-your-branch
- [x] "our wiki" - https://github.com/pfitsplus/technical-resources/wiki
- [x] "`main`"  - /tree/main

**Comment by harshav1989** [comment]
i'd like to help!

**Comment by sabaronett** [comment]
Thanks for identifying these, @wlyra. Resolved in 24af0e4.
